#!/bin/bash
# usage:
    # get hangman screen shot on clipboard
    # gah
    # paste clipboard into hangman

pushd $(dirname $BASH_SOURCE) > /dev/null
./gah.py > gah.out
echo $(wc -l < gah.out) words try $(pbpaste)
head -3 gah.out
popd > /dev/null
