#!/bin/bash
# usage:
    # get hangman screen shot on clipboard
    # hg
    # paste clipboard into hangman

pushd $(dirname $BASH_SOURCE) > /dev/null
./hg.py > hg.out
wc -l < hg.out
head -3 hg.out
popd > /dev/null
