#!/bin/bash : wordle guess
# usage: wlg green yellow black, e.g. wl ar ....e st 
OP="-e /^$1/!d -e /[$3]/d" PD='' MATCHES=wl.last
for CH in $(grep -o . <<< $2) # for each yellow
do
    [ $CH = '.' ] || OP="-e /^$PD$CH/d -e /$CH/!d $OP"
    PD=$PD. # prefix dots for pattern
done
test -f $MATCHES -a $# -gt 3 && $SOURCE=$MATCHES
sed $OP ${4:-$BASH_SOURCE.dat} > $MATCHES
# pick guess from matches. first get letters in order most frequent first
letters=$(grep -o . $MATCHES | sort | uniq -c | sort -nr | tr -d '[0-9]')
WITH_LETTER=$(mktemp) # subset containing letter
for letter in $letters; do # if letter has matches, use them as new subset
    grep $letter $MATCHES >$WITH_LETTER && mv $WITH_LETTER $MATCHES
done
head -1 $MATCHES # suggested guess
