#!/bin/bash
# usage: wordle_grep green yellow black, e.g. wordle_grep .a.r ....e st
# needs three letter occurrence sequences, using dots to specify location
OP="-e /^${1}/!d -e /[${3:-=}]/d"
PD='' # initialize prefix dots needed for yellow character filtering
for CH in $(grep -o . <<< ${2:-.}) # for each yellow
do # if not dot add filter to delete words without the yellow character
    [ $CH = '.' ] || OP="$OP -e /$CH/!d -e /^$PD$CH/d"
    PD=$PD. # to delete words with character at same position
done
sed $OP ${4:-$BASH_SOURCE.dat}
